name: Sample actions

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        env:
          SECRET_SETTING: ${{ secrets.PUBLIC_KEY }}
        run: echo SECRET_SETTING
        # run: scp -i ${{ secrets.PUBLIC_KEY }} ./index.html ${{ secrets.HOST }}:/home/ec2-user/